### ISSUE TITLE
Design website (Version 1.0)

### ISSUE THREAD

**Issue by emilyki** [cec2019/website#2]
- Design of the website (how the big picture 🖼would look like)
- Prepare assets if needed ✨
- Create issues once the designs are finalized 🗒

**Comment by emilyki** [comment]
FYI, the list of "sections/pieces of work" that we had from the previous project was:
- Navigation Bar
- About
- Competition Categories
- Schedule
- Sponsors
- Contact
- Bilingual Support (ie. French)
- Landing animation (optional I think, depends on how the design goes)
- Registration portal + dashboard for next releases perhaps? (TBD)

**Comment by tiffanynwyeung** [comment]
Ryerson's version of CEC last year (laggy tbh): https://web.archive.org/web/20171216040043/http://cec.cfes.ca:80/home

**Comment by tiffanynwyeung** [comment]
We should add some way to create easy localisation/i18n so we can simply replace en/fr content without duplicating code. looking into jekyll plugins, will update in the morning. also, we should deploy this on [netlify](https://netlify.com), since we're using a lot of custom plugins and github pages (as far as i remember) doesn't support that.

**Comment by emilyki** [comment]
Closing this issue now that the website is at a good state. Thanks for your work @tiffanynwyeung 😄
